## task file for ccoms-deployment
--- 
- name: "Create /data1 dir on k8s master node"
  file:
    path: /data1
    state: directory

- name: "Tacking helm checkout"
  git:
    repo: '{{ helm_repo }}'
    dest: "/data1/helm_charts"
    clone: yes
 
- replace:
    path: "/data1/helm_charts/common/values.yaml"
    regexp: 'app.profile:.*'
    replace: 'app.profile: {{ PROFILE }}'

- replace:
    path: "/data1/helm_charts/common/values.yaml"
    regexp: '^profile:.*'
    replace: 'profile: {{ PROFILE }}'

- name: "Deploying CCOMS application using helm"
  shell: |
    /data1/helm_charts/deploy_ccoms_app.sh -n {{ namespace }}
  register: deploy_logs

- name: "Printing error messgae"
  debug:
    msg: "{{ deploy_logs }}"

- name: "Remove helm charts"
  file:
    path: /data1
    state: absent
